schema_version = "1.0.0"

id = "comfyui-material"
type = "add-on"
version = "1.0.0-241210" # X.Y.Z-YYYYMMDD, must have a dash instead of a dot

name = "ComfyUI material creator"
tagline = "Create materials with ComfyUI"
maintainer = "Miguel Marco <mmarco@unizar.es>"
website = ""

tags = ["Materials"]
permissions = ["files", "network"]
blender_version_min = "4.0.0"

license = ["SPDX:GPL-3.0",]
copyright = ["Miguel Marco",]
